# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东保价

on:
    workflow_dispatch:
    schedule:
        - cron: "41 7,8,20 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_work_price

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【京东保价】"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  JD_USER_AGENT: ${{ github.event.client_payload.JD_USER_AGENT || secrets.JD_USER_AGENT }}
                  PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ github.event.client_payload.BARK_SOUND || secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ github.event.client_payload.DD_BOT_TOKEN || secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ github.event.client_payload.DD_BOT_SECRET || secrets.DD_BOT_SECRET }}
                  IGOT_PUSH_KEY: ${{ github.event.client_payload.IGOT_PUSH_KEY || secrets.IGOT_PUSH_KEY }}
                  QQ_SKEY: ${{ github.event.client_payload.QQ_SKEY || secrets.QQ_SKEY }}
                  QQ_MODE: ${{ github.event.client_payload.QQ_MODE || secrets.QQ_MODE }}
                  QYWX_KEY: ${{ github.event.client_payload.QYWX_KEY || secrets.QYWX_KEY }}
                  QYWX_AM: ${{ github.event.client_payload.QYWX_AM || secrets.QYWX_AM }}
                  PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}
                  JD_TRY: ${{ github.event.client_payload.JD_TRY || secrets.JD_TRY }}
                  JD_TRY_TOTALPAGES: ${{ github.event.client_payload.JD_TRY_TOTALPAGES || secrets.JD_TRY_TOTALPAGES }}
                  JD_TRY_UNIFIED: ${{ github.event.client_payload.JD_TRY_UNIFIED || secrets.JD_TRY_UNIFIED }}
                  JD_TRY_PRICE: ${{ github.event.client_payload.JD_TRY_PRICE || secrets.JD_TRY_PRICE }}
                  JD_TRY_TABID: ${{ github.event.client_payload.JD_TRY_TABID || secrets.JD_TRY_TABID }}
                  JD_TRY_TITLEFILTERS: ${{ github.event.client_payload.JD_TRY_TITLEFILTERS || secrets.JD_TRY_TITLEFILTERS }}
                  JD_TRY_TRIALPRICE: ${{ github.event.client_payload.JD_TRY_TRIALPRICE || secrets.JD_TRY_TRIALPRICE }}
                  JD_TRY_MINSUPPLYNUM: ${{ github.event.client_payload.JD_TRY_MINSUPPLYNUM || secrets.JD_TRY_MINSUPPLYNUM }}
                  JD_TRY_APPLYNUMFILTER: ${{ github.event.client_payload.JD_TRY_APPLYNUMFILTER || secrets.JD_TRY_APPLYNUMFILTER }}
                  JD_TRY_APPLYINTERVAL: ${{ github.event.client_payload.JD_TRY_APPLYINTERVAL || secrets.JD_TRY_APPLYINTERVAL }}
                  JD_TRY_MAXLENGTH: ${{ github.event.client_payload.JD_TRY_MAXLENGTH || secrets.JD_TRY_MAXLENGTH }}
                  JD_TRY_PASSZC: ${{ github.event.client_payload.JD_TRY_PASSZC || secrets.JD_TRY_PASSZC }}
                  JD_TRY_PLOG: ${{ github.event.client_payload.JD_TRY_PLOG || secrets.JD_TRY_PLOG }}
                  JD_TRY_WHITELIST: ${{ github.event.client_payload.JD_TRY_WHITELIST || secrets.JD_TRY_WHITELIST }}
                  JD_TRY_WHITELISTKEYWORDS: ${{ github.event.client_payload.JD_TRY_WHITELISTKEYWORDS || secrets.JD_TRY_WHITELISTKEYWORDS }}
                  JD_TRY_SENDNUM: ${{ github.event.client_payload.JD_TRY_SENDNUM || secrets.JD_TRY_SENDNUM }}
                  SYNCURL: https://github.com/ZFeng1005/MyScripts/raw/main/jd_work_price.js
